export type Color =
  // Common Colors
  | 'white'
  | 'black'
  // Gray Clors
  | 'gray10'
  | 'gray20'
  | 'gray30'
  | 'gray40'
  | 'gray50'
  | 'gray60'
  | 'gray70'
  | 'gray80'
  | 'gray90'
  // Primary Colors
  | 'primary10'
  | 'primary20'
  | 'primary30'
  | 'primary40'
  | 'primary50'
  | 'primary60'
  | 'primary70'
  | 'primary80'
  | 'primary90'
  | 'primary100'
  // Secondary Colors
  | 'secondary10'
  | 'secondary20'
  | 'secondary30'
  | 'secondary40'
  | 'secondary50'
  | 'secondary60'
  | 'secondary70'
  | 'secondary80'
  | 'secondary90'
  | 'secondary100'
  // System Colors
  | 'point'
  | 'point-bg'
  | 'point-txt'
  | 'danger'
  | 'danger-bg'
  | 'danger-txt'
  | 'warning'
  | 'warning-bg'
  | 'warning-txt'
  | 'success'
  | 'success-bg'
  | 'success-txt'
  | 'info'
  | 'info-bg'
  | 'info-txt'
  | 'disabled'
  | 'disabled-bg'
  | 'disabled-txt';
